/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * How geographically granular the underlying data is.
 */
export type GeographyCoverage = "Global" | "Regional" | "Country";
/**
 * How finely the underlying data is resolved over time.
 */
export type TimeResolution =
  | "No information"
  | "Single year (2050)"
  | "Medium-term"
  | "10-year"
  | "5-10-year"
  | "5-year"
  | "1-year"
  | "Other";
/**
 * Where the data can be obtained, and in what form.
 */
export type DataFormat =
  "In tool" | "Tabular in publication" | "Text in publication";
/**
 * Whether reaching the data at the publisher costs money. Null when we host it.
 */
export type Access = "Free" | "Paywalled" | null;

/**
 * The closed vocabularies describing how a metric's underlying data can be obtained (#870).
 */
export interface DataAvailabilityV1 {
  geographyCoverage: GeographyCoverage;
  timeResolution: TimeResolution;
  dataFormat: DataFormat;
  access: Access;
}
