/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Display name of the metric as the Data Availability table keys its rows.
 */
export type DisplayName =
  | "Emissions intensity"
  | "Absolute Emissions"
  | "Capacity"
  | "Generation"
  | "Technology mix"
  | "Transmission lines"
  | "Technology cost"
  | "Investment requirement"
  | "Asset lifetime"
  | "Emissions intensity (total)"
  | "Emissions intensity (primary)"
  | "Emissions intensity (secondary)"
  | "Absolute emissions"
  | "Technology mix (production by route)"
  | "Steel production by technology (production route)"
  | "Scrap share"
  | "Emissions intensity (passenger)"
  | "Emissions intensity (freight)"
  | "Absolute emissions Well-to-Wheel (passenger)"
  | "Absolute emissions Well-to-Wheel (freight)"
  | "Total demand (passenger)"
  | "Total demand (freight)"
  | "Demand by propulsion technology (passenger)"
  | "Demand by propulsion technology (freight)"
  | "Demand share by propulsion technology (passenger)"
  | "Demand share by propulsion technology (freight)";

/**
 * The metric a dataAvailability row describes — the cookbook's 'Metrics – Extended' (#870).
 */
export interface DataAvailabilityMetricV1 {
  displayName: DisplayName;
}
