/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * How finely the underlying data is resolved over time. Where a pathway resolves a metric differently for different geographies, the most granular resolution available is the one recorded.
 */
export type TimeResolution =
  | "2050 data point"
  | "Medium-term data point"
  | "10-year steps"
  | "5-year steps"
  | "1-year steps"
  | "5/10-year steps"
  | "Other time resolution"
  | "Unspecified"
  | "Not covered";
/**
 * In what form the source publication makes the metric's values available to a reader. Where values appear in more than one form the most extractable wins: Tabular before Text before Figure.
 */
export type DataFormat = "Tabular" | "Text" | "Figure" | "Not covered";
/**
 * Granularity values that are not technologies. A row's `granularity` is a flat array drawn from this vocabulary or from the sector's technologies, depending on the metric.
 */
export type GranularityBreakdown =
  | "Scope 1"
  | "Scope 1 & 2"
  | "Scope 1, 2 & 3"
  | "Scope 1 & 3"
  | "Unspecified"
  | "Not covered";

/**
 * The closed vocabularies describing how a metric's underlying data can be obtained (#870). Values follow cookbook tpr_cookbook_20260924; see docs/cookbook/split/data_availability in RMI/tpr-tpc.
 */
export interface DataAvailabilityV1 {
  timeResolution: TimeResolution;
  dataFormat: DataFormat;
  granularityBreakdown: GranularityBreakdown;
}
