/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A single ISO-3166-1 alpha-2 country code (e.g., US, DE). Only 2-letter codes are accepted; do not use full country names or 3-letter codes. 2-letter strings that do not map to a country (e.g., EU) will throw downstream errors.
 */
export type CountryCode = import("./countryCode.v1").CountryCodeV1;
/**
 * A single ISO-3166-1 alpha-2 country code (e.g., US, DE). Only 2-letter codes are accepted; do not use full country names or 3-letter codes. 2-letter strings that do not map to a country (e.g., EU) will throw downstream errors.
 */
export type CountryCode1 = import("./countryCode.v1").CountryCodeV1;

/**
 * Geographical coverage of a pathway. 'global' marks whole-world coverage (a literal flag, not a list of every country); 'regions' maps an author-defined region label, kept as named in the source publication, to the ISO-3166-1 alpha-2 country codes it contains (member arrays may be empty when the publication provides no mapping); 'country' lists standalone ISO-3166-1 alpha-2 country codes.
 */
export interface GeographyV1 {
  /**
   * True if the pathway covers the entire world.
   */
  global?: boolean;
  /**
   * Map from an author-defined region label (as named in the publication) to the ISO-3166-1 alpha-2 country codes in that region. Member arrays may be empty when the publication does not provide a mapping.
   */
  regions?: {
    [k: string]: CountryCode[];
  };
  /**
   * Standalone ISO-3166-1 alpha-2 country codes covered by the pathway.
   */
  country?: CountryCode1[];
}
