/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Display name of the metric
 */
export type DisplayName =
  | "Emissions Intensity"
  | "Capacity"
  | "Generation"
  | "Technology Mix"
  | "Absolute Emissions";

/**
 * Common definition of a metric used across pathway schemas.
 */
export interface MetricV1 {
  displayName: DisplayName;
}
