/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The sector axis of a scoped keyFeatures entry: one of the sector display names, or the widest sentinel 'cross-sector'.
 */
export type ScopeSectorV2 =
  | "cross-sector"
  | "Land Use"
  | "Agriculture"
  | "Buildings"
  | "Steel"
  | "Cement"
  | "Chemicals"
  | "Coal Mining"
  | "Oil (Upstream)"
  | "Gas (Upstream)"
  | "Power"
  | "Automotive"
  | "Aviation"
  | "Rail"
  | "Shipping"
  | "Other";
