/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Display name of the sector segment as presented in tables.
 */
export type DisplayName =
  | "No information"
  | "Unspecified"
  | "Not covered"
  | "Upstream energy and fuels"
  | "Passenger transport"
  | "Freight transport"
  | "Fuel extraction and processing"
  | "Power generation"
  | "Energy storage"
  | "Transmission and distribution"
  | "Mining"
  | "Ironmaking"
  | "Steelmaking"
  | "Downstream";

/**
 * Segments within a sector
 */
export interface SectorSegmentV1 {
  displayName: DisplayName;
}
