/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Display name of a sector.
 */
export type DisplayName =
  | "Land Use"
  | "Agriculture"
  | "Buildings"
  | "Steel"
  | "Cement"
  | "Chemicals"
  | "Coal Mining"
  | "Oil (Upstream)"
  | "Gas (Upstream)"
  | "Power"
  | "Automotive"
  | "Aviation"
  | "Rail"
  | "Shipping"
  | "Other";

/**
 * Common definition of a sector used across pathway schemata.
 */
export interface SectorV1 {
  displayName: DisplayName;
}
