/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Display name of the sector segment as presented in tables.
 */
export type DisplayName =
  | "No information"
  | "Power generation"
  | "Storage"
  | "Transmission & Distribution";

/**
 * Segments within a sector
 */
export interface SectorSegmentV1 {
  displayName: DisplayName;
}
