/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Display name of the technology as presented in charts or tables.
 */
export type DisplayName =
  | "Precision Agriculture"
  | "Agroforestry"
  | "Bioenergy Crops"
  | "Energy Efficiency"
  | "Smart Grids"
  | "Renewable Heating"
  | "Heat Pumps"
  | "Building Automation"
  | "Smart Appliances"
  | "Insulation"
  | "Carbon Capture and Storage"
  | "Electrification"
  | "Process Optimization"
  | "Hydrogen Use"
  | "Coal"
  | "Oil"
  | "Gas"
  | "Wind"
  | "Solar"
  | "Nuclear"
  | "Biomass"
  | "Hydro"
  | "Renewables"
  | "Electric Vehicles"
  | "Hydrogen Vehicles"
  | "Biofuels"
  | "Public Transport"
  | "Active Mobility"
  | "Aviation Efficiency"
  | "Maritime Efficiency"
  | "Geothermal"
  | "Energy storage"
  | "BOF"
  | "BF-BOF"
  | "BF-BOF+PCI"
  | "BF-BOF+CCUS"
  | "DRI-Melt-BOF"
  | "EAF"
  | "Scrap-EAF"
  | "DRI-EAF"
  | "DRI-EAF+H2"
  | "DRI-EAF+CCS"
  | "Electrolyser/Electrowinning"
  | "Jet Fuel"
  | "SAF"
  | "Electricity"
  | "Hydrogen"
  | "HEFA"
  | "PtL"
  | "AtJ"
  | "Other";

/**
 * Technologies for sectors
 */
export interface TechnologyV1 {
  displayName: DisplayName;
}
