/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Name of the pathway.
 */
export type Label = import("./common/label.v1").LabelV1;
/**
 * Bibliographic information about the report or dataset.
 */
export type Publication = import("./common/publication.v1").PublicationV1;
/**
 * Geographical areas that the pathway covers.
 */
export type Geography = import("./common/geography.v1").GeographyV1;
/**
 * The sector axis of a scoped keyFeatures entry: one of the sector display names, or the widest sentinel 'cross-sector'.
 */
export type ScopeSector = import("./common/scopeSector.v2").ScopeSectorV2;
/**
 * The geography axis of a scoped keyFeatures entry: 'Global', 'cross-region', an ISO-3166-1 alpha-2 country code, or an author-defined region label.
 */
export type ScopeGeography =
  import("./common/scopeGeography.v2").ScopeGeographyV2;
/**
 * The sector axis of a scoped keyFeatures entry: one of the sector display names, or the widest sentinel 'cross-sector'.
 */
export type ScopeSector1 = import("./common/scopeSector.v2").ScopeSectorV2;
/**
 * The geography axis of a scoped keyFeatures entry: 'Global', 'cross-region', an ISO-3166-1 alpha-2 country code, or an author-defined region label.
 */
export type ScopeGeography1 =
  import("./common/scopeGeography.v2").ScopeGeographyV2;
/**
 * The sector axis of a scoped keyFeatures entry: one of the sector display names, or the widest sentinel 'cross-sector'.
 */
export type ScopeSector2 = import("./common/scopeSector.v2").ScopeSectorV2;
/**
 * The geography axis of a scoped keyFeatures entry: 'Global', 'cross-region', an ISO-3166-1 alpha-2 country code, or an author-defined region label.
 */
export type ScopeGeography2 =
  import("./common/scopeGeography.v2").ScopeGeographyV2;
/**
 * The sector axis of a scoped keyFeatures entry: one of the sector display names, or the widest sentinel 'cross-sector'.
 */
export type ScopeSector3 = import("./common/scopeSector.v2").ScopeSectorV2;
/**
 * The geography axis of a scoped keyFeatures entry: 'Global', 'cross-region', an ISO-3166-1 alpha-2 country code, or an author-defined region label.
 */
export type ScopeGeography3 =
  import("./common/scopeGeography.v2").ScopeGeographyV2;
/**
 * The sector axis of a scoped keyFeatures entry: one of the sector display names, or the widest sentinel 'cross-sector'.
 */
export type ScopeSector4 = import("./common/scopeSector.v2").ScopeSectorV2;
/**
 * The geography axis of a scoped keyFeatures entry: 'Global', 'cross-region', an ISO-3166-1 alpha-2 country code, or an author-defined region label.
 */
export type ScopeGeography4 =
  import("./common/scopeGeography.v2").ScopeGeographyV2;
/**
 * The sector axis of a scoped keyFeatures entry: one of the sector display names, or the widest sentinel 'cross-sector'.
 */
export type ScopeSector5 = import("./common/scopeSector.v2").ScopeSectorV2;
/**
 * The geography axis of a scoped keyFeatures entry: 'Global', 'cross-region', an ISO-3166-1 alpha-2 country code, or an author-defined region label.
 */
export type ScopeGeography5 =
  import("./common/scopeGeography.v2").ScopeGeographyV2;
/**
 * The sector axis of a scoped keyFeatures entry: one of the sector display names, or the widest sentinel 'cross-sector'.
 */
export type ScopeSector6 = import("./common/scopeSector.v2").ScopeSectorV2;
/**
 * The geography axis of a scoped keyFeatures entry: 'Global', 'cross-region', an ISO-3166-1 alpha-2 country code, or an author-defined region label.
 */
export type ScopeGeography6 =
  import("./common/scopeGeography.v2").ScopeGeographyV2;
/**
 * Defines which greenhouse gases are covered in the pathway's modeled emissions.
 */
export type EmissionsScope =
  import("./common/emissionsScope.v1").EmissionsScopeV1;
/**
 * The sector axis of a scoped keyFeatures entry: one of the sector display names, or the widest sentinel 'cross-sector'.
 */
export type ScopeSector7 = import("./common/scopeSector.v2").ScopeSectorV2;
/**
 * The geography axis of a scoped keyFeatures entry: 'Global', 'cross-region', an ISO-3166-1 alpha-2 country code, or an author-defined region label.
 */
export type ScopeGeography7 =
  import("./common/scopeGeography.v2").ScopeGeographyV2;
/**
 * The sector axis of a scoped keyFeatures entry: one of the sector display names, or the widest sentinel 'cross-sector'.
 */
export type ScopeSector8 = import("./common/scopeSector.v2").ScopeSectorV2;
/**
 * The geography axis of a scoped keyFeatures entry: 'Global', 'cross-region', an ISO-3166-1 alpha-2 country code, or an author-defined region label.
 */
export type ScopeGeography8 =
  import("./common/scopeGeography.v2").ScopeGeographyV2;
/**
 * The sector axis of a scoped keyFeatures entry: one of the sector display names, or the widest sentinel 'cross-sector'.
 */
export type ScopeSector9 = import("./common/scopeSector.v2").ScopeSectorV2;
/**
 * The geography axis of a scoped keyFeatures entry: 'Global', 'cross-region', an ISO-3166-1 alpha-2 country code, or an author-defined region label.
 */
export type ScopeGeography9 =
  import("./common/scopeGeography.v2").ScopeGeographyV2;
/**
 * The sector axis of a scoped keyFeatures entry: one of the sector display names, or the widest sentinel 'cross-sector'.
 */
export type ScopeSector10 = import("./common/scopeSector.v2").ScopeSectorV2;
/**
 * The geography axis of a scoped keyFeatures entry: 'Global', 'cross-region', an ISO-3166-1 alpha-2 country code, or an author-defined region label.
 */
export type ScopeGeography10 =
  import("./common/scopeGeography.v2").ScopeGeographyV2;
/**
 * Geography this row applies to. Same scope token as keyFeatures, so the table can be filtered by the detail page's geography selection (#872) using the existing scope helpers.
 */
export type ScopeGeography11 =
  import("./common/scopeGeography.v2").ScopeGeographyV2;

/**
 * A schema for the pathway metadata dataset in TPR.
 */
export interface PathwayMetadataV2 {
  /**
   * URI of the schema that validates this document (see https://json-schema.org/).
   */
  $schema?: string;
  /**
   * The unique identifier for a pathway.
   */
  id: string;
  name: Label;
  /**
   * Brief description of the pathway.
   */
  description: string;
  publication: Publication;
  /**
   * Type of the pathway.
   */
  pathwayType: "Normative" | "Exploratory" | "Predictive";
  /**
   * Year by which net zero is reached in the pathway. If Pathway does not reach net zero, this field should be omitted.
   */
  modelYearNetzero?: number;
  /**
   * Year from which the model starts.
   */
  modelYearStart?: number;
  /**
   * Year in which the model ends.
   */
  modelYearEnd?: number;
  /**
   * Modeled temperature increase expected by the pathway (in degrees Celsius).
   */
  modelTempIncrease?: number;
  geography: Geography;
  /**
   * Sectors that the pathway covers.
   */
  sectors: {
    /**
     * Display name of a sector.
     */
    name:
      | "Land Use"
      | "Agriculture"
      | "Buildings"
      | "Steel"
      | "Cement"
      | "Chemicals"
      | "Coal Mining"
      | "Oil (Upstream)"
      | "Gas (Upstream)"
      | "Power"
      | "Automotive"
      | "Aviation"
      | "Rail"
      | "Shipping"
      | "Other";
    /**
     * Technologies applicable to this sector.
     */
    technologies: (
      | "Precision Agriculture"
      | "Agroforestry"
      | "Bioenergy Crops"
      | "Energy Efficiency"
      | "Smart Grids"
      | "Renewable Heating"
      | "Heat Pumps"
      | "Building Automation"
      | "Smart Appliances"
      | "Insulation"
      | "Carbon Capture and Storage"
      | "Electrification"
      | "Process Optimization"
      | "Hydrogen Use"
      | "Coal"
      | "Oil"
      | "Gas"
      | "Wind"
      | "Solar"
      | "Nuclear"
      | "Biomass"
      | "Hydro"
      | "Renewables"
      | "Electric Vehicles"
      | "Hydrogen Vehicles"
      | "Biofuels"
      | "Public Transport"
      | "Active Mobility"
      | "Aviation Efficiency"
      | "Maritime Efficiency"
      | "Other"
    )[];
  }[];
  /**
   * Narrative description of the pathway. Replaces v1's expertOverview: in the v1 corpus this is the '#### Pathway Description' section of it. v1's separate pathwayOverview field is retired without replacement, not merged in here -- the two texts restate each other, so merging them read as immediate self-repetition. null means no description is available.
   */
  pathwayDescription: string | null;
  metric: import("./common/metric.v1").MetricV1["displayName"][];
  /**
   * Key features of the pathway. Every field is an array of {sector, geography, value} entries (#858), so a pathway can hold different values for different parts of its coverage. A non-varying feature carries exactly one entry at the widest applicable scope: sector 'cross-sector' for a multi-sector pathway else its lone sector, and geography 'Global' else the pathway's widest declared region or country. An entry that is absent at some scope means the resolver keeps broadening until it finds one; an explicit "No information" value is a real authored value that terminates that fallback chain and displays at its own scope. An empty array means nothing is authored at any scope.
   */
  keyFeatures: {
    /**
     * Describes the overall trend of greenhouse gas emissions over time, from continued growth to rapid decline. Scoped: see keyFeatures.
     */
    emissionsTrajectory: {
      sector: ScopeSector;
      geography: ScopeGeography;
      value:
        | "No information"
        | "Significant increase"
        | "Moderate increase"
        | "Minor increase"
        | "Low or no change"
        | "Minor decrease"
        | "Moderate decrease"
        | "Significant decrease";
    }[];
    /**
     * Indicates how efficiently energy is used to produce economic output across the sectors covered in the pathway. Scoped: see keyFeatures.
     */
    energyEfficiency: {
      sector: ScopeSector1;
      geography: ScopeGeography1;
      value:
        | "No information"
        | "Significant deterioration"
        | "Moderate deterioration"
        | "Minor deterioration"
        | "Low or no change"
        | "Minor improvement"
        | "Moderate improvement"
        | "Significant improvement";
    }[];
    /**
     * Captures the change in total energy consumption, driven by factors such as socio-economic development, technology shifts and consumer behavior. Scoped: see keyFeatures.
     */
    energyDemand: {
      sector: ScopeSector2;
      geography: ScopeGeography2;
      value:
        | "No information"
        | "Significant decrease"
        | "Moderate decrease"
        | "Minor decrease"
        | "Low or no change"
        | "Minor increase"
        | "Moderate increase"
        | "Significant increase";
    }[];
    /**
     * Represents the extent to which energy end-uses transition from fossil fuels to electricity. Scoped: see keyFeatures.
     */
    electrification: {
      sector: ScopeSector3;
      geography: ScopeGeography3;
      value:
        | "No information"
        | "Significant decrease"
        | "Moderate decrease"
        | "Minor decrease"
        | "Low or no change"
        | "Minor increase"
        | "Moderate increase"
        | "Significant increase";
    }[];
    /**
     * Identifies the types of policies modeled as drivers of the pathway, such as carbon pricing, subsidies, or mandated phaseouts of specific technologies. Scoped: see keyFeatures.
     */
    policyTypes: {
      sector: ScopeSector4;
      geography: ScopeGeography4;
      /**
       * @minItems 1
       */
      value: [
        (
          | "No information"
          | "Carbon price"
          | "Feed-in tariffs"
          | "Performance standards"
          | "Phaseout dates"
          | "Subsidies"
          | "Target technology shares"
          | "Other"
          | "None"
        ),
        ...(
          | "No information"
          | "Carbon price"
          | "Feed-in tariffs"
          | "Performance standards"
          | "Phaseout dates"
          | "Subsidies"
          | "Target technology shares"
          | "Other"
          | "None"
        )[],
      ];
    }[];
    /**
     * Describes how technology costs evolve over time, from static cost assumptions to rapidly declining costs (e.g., via learning curves). Scoped: see keyFeatures.
     */
    technologyCostTrend: {
      sector: ScopeSector5;
      geography: ScopeGeography5;
      value: "No information" | "Increase" | "Low or no change" | "Decrease";
    }[];
    /**
     * Defines which greenhouse gases are covered in the pathway's modeled emissions. Scoped: see keyFeatures.
     */
    emissionsScope: {
      sector: ScopeSector6;
      geography: ScopeGeography6;
      value: EmissionsScope;
    }[];
    /**
     * Represents the overall stringency and intent of modeled policies relative to climate targets, often reflecting if and how far the included policies go beyond currently legislated ones. Scoped: see keyFeatures.
     */
    policyAmbition: {
      sector: ScopeSector7;
      geography: ScopeGeography7;
      value:
        | "No information"
        | "No policies included"
        | "Current/legislated policies"
        | "Current and drafted policies"
        | "NDCs, unconditional only"
        | "NDCs incl. conditional targets"
        | "High ambition policies"
        | "Other policy ambition";
    }[];
    /**
     * Specifies the level of granularity in cost data, such as total system costs or detailed CAPEX/OPEX breakdowns. Scoped: see keyFeatures.
     */
    technologyCostsDetail: {
      sector: ScopeSector8;
      geography: ScopeGeography8;
      value:
        | "No information"
        | "Total costs"
        | "Capital costs, O&M, etc."
        | "Other cost breakdown";
    }[];
    /**
     * Lists emerging or breakthrough technologies that are explicitly modeled within the pathway. These are considered in technology deployment too. Scoped: see keyFeatures.
     */
    newTechnologiesIncluded: {
      sector: ScopeSector9;
      geography: ScopeGeography9;
      /**
       * @minItems 1
       */
      value: [
        (
          | "No information"
          | "No new technologies"
          | "CCUS"
          | "DAC"
          | "Green H2/ammonia"
          | "SAF"
          | "Battery storage"
          | "EGS/AGS"
          | "Other new technologies"
        ),
        ...(
          | "No information"
          | "No new technologies"
          | "CCUS"
          | "DAC"
          | "Green H2/ammonia"
          | "SAF"
          | "Battery storage"
          | "EGS/AGS"
          | "Other new technologies"
        )[],
      ];
    }[];
    /**
     * Summarizes how investment requirements are quantified, from total system to sector-level or supply-chain detail. Scoped: see keyFeatures.
     */
    investmentNeeds: {
      sector: ScopeSector10;
      geography: ScopeGeography10;
      value:
        | "No information"
        | "Total investment"
        | "By sector"
        | "By sector, part of value chain"
        | "By technology"
        | "By tech, part of value chain";
    }[];
  };
  /**
   * The drivers that shape this pathway's outcomes. Every field is required but nullable: null means the driver is not a core driver for this pathway, as distinct from a driver that is present but undescribed.
   */
  coreDrivers: {
    /**
     * Policies modeled as a driver of this pathway.
     */
    policies: string | null;
    /**
     * Emissions targets or constraints driving this pathway.
     */
    emissionsTargets: string | null;
    /**
     * Technology cost assumptions driving this pathway.
     */
    technologyCosts: string | null;
    /**
     * Changes in investment driving this pathway.
     */
    investmentChange: string | null;
    /**
     * Macroeconomic assumptions driving this pathway.
     */
    macroeconomicDrivers: string | null;
    /**
     * Behavioral or demand-side shifts driving this pathway.
     */
    behavioralShifts: string | null;
    /**
     * Any other core driver of this pathway.
     */
    otherDrivers: string | null;
  };
  /**
   * Conditions the pathway's outcomes depend on. Descriptive only -- deliberately NOT part of the #869 inheritance chain, so these are not scoped by geography.
   */
  dependencies: {
    /**
     * Category of the dependency.
     */
    dependency_name:
      | "Policy strategy"
      | "Regulatory framework"
      | "Market and economics"
      | "Public acceptance"
      | "Consumer and client behavior"
      | "Infrastructure and logistics"
      | "Technology"
      | "Resource availability"
      | "Environmental impacts and ecosystem services"
      | "Labor availability";
    /**
     * What the pathway depends on, in prose.
     */
    dependency_description: string;
    /**
     * Display name of a sector.
     */
    sector:
      | "Land Use"
      | "Agriculture"
      | "Buildings"
      | "Steel"
      | "Cement"
      | "Chemicals"
      | "Coal Mining"
      | "Oil (Upstream)"
      | "Gas (Upstream)"
      | "Power"
      | "Automotive"
      | "Aviation"
      | "Rail"
      | "Shipping"
      | "Other";
    /**
     * Strength of the evidence for this dependency.
     */
    evidence_type: "Quantitative" | "Qualitative" | "Anecdotal" | "No evidence";
  }[];
  /**
   * Where and how the data behind each metric can be obtained (#870). Optional: authoring is incremental, and a pathway with no entry yet is not an invalid pathway. Absent means unknown, NOT unavailable -- `dataFormat` says unavailable.
   */
  dataAvailability?: {
    /**
     * Summary of the full timeseries file we host, plus anything that does not fit the per-metric rows. Null where there is nothing to add.
     */
    overall: string | null;
    /**
     * One row per (metricName, sector, sectorSegment, geography). Each combination may appear only once -- enforced by scripts/schema-check-files.ts, because uniqueItems compares whole entries and so permits two rows that agree on the scope and disagree on everything else.
     */
    byMetric: {
      /**
       * Metric this row describes. Must be a metric the pathway itself reports (one of its own `metric` values) and a metric of its `sector` -- both enforced by scripts/schema-check-files.ts.
       */
      metricName: import("./common/metric.v1").MetricV1["displayName"];
      /**
       * Display name of a sector.
       */
      sector: import("./common/sector.v1").SectorV1["displayName"];
      /**
       * Segment within the sector. `No information` where the sector is not segmented, or where its segments are not yet defined.
       */
      sectorSegment: import("./common/sectorSegment.v1").SectorSegmentV1["displayName"];
      geography: ScopeGeography11;
      /**
       * How geographically granular the underlying data is. A coverage class, not a scope -- `geography` above carries the scope.
       */
      geographyCoverage: "Global" | "Regional" | "Country";
      /**
       * How finely the underlying data is resolved over time.
       */
      timeResolution:
        | "No information"
        | "Single year (2050)"
        | "Medium-term"
        | "10-year"
        | "5-10-year"
        | "5-year"
        | "1-year"
        | "Other";
      /**
       * Where the data can be obtained, and in what form. `In tool` rows link to the timeseries download.
       */
      dataFormat: "In tool" | "Tabular in publication" | "Text in publication";
      /**
       * Whether reaching the data at the publisher costs money. Must be null exactly when `dataFormat` is `In tool` -- enforced by scripts/schema-check-files.ts.
       */
      access: "Free" | "Paywalled" | null;
      /**
       * Dimensions the metric is broken down by, or null where it is reported as a single series. Values are technologies of this row's sector -- enforced by scripts/schema-check-files.ts, the same rule as sectors[].technologies.
       */
      granularity:
        import("./common/technology.v1").TechnologyV1["displayName"][] | null;
      /**
       * Caveats on what the data does and does not cover, in prose. Null where there are none.
       */
      scopeLimitations: string | null;
    }[];
  };
}
