/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Bibliographic information about the report or dataset.
 */
export type Publication = import("./common/publication.v1").PublicationV1;
/**
 * Defines which greenhouse gases are covered in the pathway's modeled emissions.
 */
export type EmissionsScope =
  import("./common/emissionsScope.v1").EmissionsScopeV1;

/**
 * A schema for the pathway timeseries dataset in TPR, version 2: geography as the publication names it, and the sector segments each row covers.
 */
export interface PathwayTimeseriesV2 {
  /**
   * URI of the schema that validates this document (see https://json-schema.org/).
   */
  $schema?: string;
  /**
   * The unique identifier for a pathway.
   */
  id: string;
  /**
   * Identifiers of the associated pathways.
   */
  pathwayId: string[];
  /**
   * Name of the timeseries.
   */
  name: string;
  /**
   * Brief description of the timeseries.
   */
  description: string;
  publication: Publication;
  /**
   * Name of the associated pathway.
   */
  pathwayName: string;
  emissionsScope: EmissionsScope;
  /**
   * Array of yearly data points for each sector, technology, and metric defined in this timeseries.
   */
  data: {
    /**
     * Calendar year of the data point.
     */
    year: number;
    /**
     * Geography this data point covers, written exactly as the pathway's metadata declares it: 'Global' (when the pathway is global), one of its region labels (a key of `geography.regions`, in the publication's own wording, e.g. 'ASEAN' or 'Southeast Asia'), or an ISO-3166-1 alpha-2 country code the pathway declares (a standalone country or a member of one of its regions). Every pathway in `pathwayId` must declare it; enforced by scripts/schema-check-files.ts.
     */
    geography: string;
    /**
     * Sector to which this data point belongs (must match one of the defined sectors).
     */
    sector:
      | "landUse"
      | "agriculture"
      | "buildings"
      | "industry"
      | "steel"
      | "cement"
      | "chemicals"
      | "coalMining"
      | "oilUpstream"
      | "gasUpstream"
      | "power"
      | "automotive"
      | "transport"
      | "roadtransport"
      | "aviation"
      | "rail"
      | "shipping"
      | "other";
    /**
     * Segments of this row's sector that the data point covers, e.g. ['Power generation']. Same vocabulary as dataAvailability's sectorSegment. Members must be segments of this row's `sector`, and the sentinels (Unspecified, Not covered, No information) are not allowed: every row is actual data, so it covers a known part of the value chain. Enforced by scripts/schema-check-files.ts.
     *
     * @minItems 1
     *
     * Items: Display name of the sector segment as presented in tables.
     */
    sectorSegment: [
      import("./common/sectorSegment.v1").SectorSegmentV1["displayName"],
      ...import("./common/sectorSegment.v1").SectorSegmentV1["displayName"][],
    ];
    /**
     * Technology represented in this record (e.g., Solar, Wind, or null if sector-level only).
     */
    technology:
      | "precisionAgriculture"
      | "agroforestry"
      | "bioenergyCrops"
      | "energyEfficiency"
      | "smartGrids"
      | "renewableHeating"
      | "heatPumps"
      | "buildingAutomation"
      | "smartAppliances"
      | "insulation"
      | "carbonCaptureandStorage"
      | "electrification"
      | "processOptimization"
      | "hydrogenUse"
      | "coal"
      | "oil"
      | "gas"
      | "wind"
      | "solar"
      | "nuclear"
      | "biomass"
      | "hydro"
      | "geothermal"
      | "energyStorage"
      | "renewables"
      | "electricVehicles"
      | "hydrogenVehicles"
      | "biofuels"
      | "publicTransport"
      | "activeMobility"
      | "aviationEfficiency"
      | "maritimeEfficiency"
      | "other"
      | null;
    /**
     * Metric reported for this record (e.g., Capacity, Generation, Emissions Intensity).
     */
    metric:
      | "emissionsIntensity"
      | "capacity"
      | "generation"
      | "technologyMix"
      | "absoluteEmissions";
    /**
     * Numeric value of the metric for the given year, sector, and technology.
     */
    value: number;
    /**
     * Measurement unit associated with the metric value (e.g., GW, TWh, tCO2e).
     */
    unit: "tCO2e/MWh" | "MtCO2e" | "GW" | "TWh" | "%";
  }[];
}
