/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Bibliographic information about the report or dataset.
 */
export type Publication = import("./common/publication.v1").PublicationV1;
/**
 * Defines which greenhouse gases are covered in the pathway's modeled emissions.
 */
export type EmissionsScope =
  import("./common/emissionsScope.v1").EmissionsScopeV1;

/**
 * A schema for the pathway timeseries dataset in TPR.
 */
export interface PathwayTimeseriesV1 {
  /**
   * URI of the schema that validates this document (see https://json-schema.org/).
   */
  $schema?: string;
  /**
   * The unique identifier for a pathway.
   */
  id: string;
  /**
   * Identifiers of the associated pathways.
   */
  pathwayId: string[];
  /**
   * Name of the timeseries.
   */
  name: string;
  /**
   * Brief description of the timeseries.
   */
  description: string;
  publication: Publication;
  /**
   * Name of the associated pathway.
   */
  pathwayName: string;
  emissionsScope: EmissionsScope;
  /**
   * Array of yearly data points for each sector, technology, and metric defined in this timeseries.
   */
  data: {
    [k: string]: unknown;
  }[];
}
