---
on:
  workflow_call:
    outputs:
      has_artifact:
        description: "Whether dist.tgz was produced in this run"
        value: ${{ jobs.build-release.outputs.has_artifact }}
      version:
        description: "Version string derived in the build"
        value: ${{ jobs.build-release.outputs.version }}
      preview-version:
        description: "Version string derived in the build"
        value: ${{ jobs.build-release.outputs.preview-version }}

name: Build and Release

permissions:
  contents: read # for checkout

jobs:
  build-release:
    name: Build and Release
    outputs:
      has_artifact: ${{ steps.check_artifact.outputs.has_artifact }}
      version: ${{ steps.build-release.outputs.version }}
      preview-version: ${{ steps.build-release.outputs.preview-version }}
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          # checkout base ref for PRs, or actual branch for pushes
          ref: ${{
            (github.event_name == 'pull_request' && github.base_ref)
            || github.ref
            }}

      - name: Merge PR branch to PR target
        if: ${{ github.event_name == 'pull_request' }}
        env:
          HEAD_BRANCH: ${{ github.head_ref }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git merge "origin/$HEAD_BRANCH"

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm clean-install

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Build & Release
        id: build-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VITE_BUILD_MODE: |
            ${{
              (github.event_name == 'push' && github.ref_name) ||
              (github.event_name == 'pull_request' && github.base_ref == 'production' && github.head_ref) ||
              (github.event_name == 'pull_request' && format('{0}-{1}', 'pr', github.event.pull_request.number)) ||
              github.ref_name
            }}
          VITE_BUILD_ID: gha-${{ github.run_id }}.${{ github.run_attempt }}
          VITE_GITHUB_ACTOR: ${{ github.actor }}
          VITE_GITHUB_EVENT_NAME: ${{ github.event_name }}
          VITE_GITHUB_REPOSITORY: ${{ github.repository }}
          VITE_GITHUB_REF: ${{ github.ref }}
          VITE_GITHUB_SHA: ${{ github.sha }}
          VITE_GITHUB_HEAD_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
          VITE_GITHUB_WORKFLOW: ${{ github.workflow }}
          VITE_GITHUB_WORKFLOW_REF: ${{ github.workflow_ref }}
          VITE_GITHUB_WORKFLOW_SHA: ${{ github.workflow_sha }}
          VITE_GITHUB_RUN_ID: ${{ github.run_id }}
          VITE_GITHUB_RUN_NUMBER: ${{ github.run_number }}
          VITE_GITHUB_RUN_ATTEMPT: ${{ github.run_attempt }}
          VITE_BUILD_MACHINE_NAME: ${{ runner.name }}
          VITE_BUILD_OS: ${{ runner.os }}
          VITE_BUILD_OS_VERSION: ${{ runner.os-version }}
          VITE_BUILD_ARCH: ${{ runner.arch }}
          VITE_GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
        run: |
          echo "Build ID: $VITE_BUILD_ID"
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "unsetting GITHUB_ACTIONS"
            unset GITHUB_ACTIONS
            echo "dry-running semantic-release"
            npx semantic-release \
              --dry-run \
              --no-ci | \
              tee /tmp/semantic-release-raw.txt
            echo "Inspecting output for version"
            LOG="/tmp/semantic-release-raw.txt"
            VERSION=$(grep -oE 'Release note for version [^:]+' "$LOG" 2>/dev/null \
              | sed -E 's/.*Release note for version ([^:]+).*/\1/' \
              || true)
            if [[ -z "$VERSION" ]]; then
              echo "No release note, looking for current version"
              VERSION=$(grep -oE 'associated with version  [^:]+ on branch' "$LOG" 2>/dev/null \
                | sed -E 's/.*associated with version  ([^:]+) on branch.*/\1/' \
                || true)
            fi
            if [[ -z "$VERSION" ]]; then
              echo "No current version found, using default"
              VERSION=0.0.0-local
            fi
            echo "VERSION=$VERSION"
            echo "version=$VERSION" >> "$GITHUB_OUTPUT"
            echo "preparing preview version"
            PREVIEW_VERSION="$VERSION-pr.${{ github.event.pull_request.number }}.${{ github.run_number }}"
            echo "preview-version=$PREVIEW_VERSION"
            echo "preview-version=$PREVIEW_VERSION" >> "$GITHUB_OUTPUT"
            echo "versioning with npm version"
            npm version "$PREVIEW_VERSION" --no-git-tag-version
            jq -r '.version' package.json  # sanity check
            echo "preparing tarball"
            npm run prepare:tarball
          else
            echo "running semantic release"
            npx semantic-release
          fi

      - name: Check for dist.tgz
        id: check_artifact
        shell: bash
        run: |
          if [[ -f dist.tgz ]]; then
            echo "has_artifact=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_artifact=false" >> "$GITHUB_OUTPUT"
          fi

        # Reuse the artifact for downstream deploy
      - name: Upload dist.tgz as workflow artifact
        if: ${{ steps.check_artifact.outputs.has_artifact == 'true' }}
        uses: actions/upload-artifact@v7
        with:
          name: dist-tgz
          path: dist.tgz
          if-no-files-found: error

      - name: prepare semantic-release output for comment
        if: ${{ github.event_name == 'pull_request' }}
        env:
          HEAD_BRANCH: ${{ github.head_ref }}
        run: |
          sed -n \
            -e '1,/Release note for version/d; p' \
            /tmp/semantic-release-raw.txt \
          | sed -E \
            -e  's/^[[:space:]]*\*/\*/' \
          | sed \
            -e "1s|\(\.\.\.[^)]*\))|...${HEAD_BRANCH} )|" \
            -e "1s/[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}/$(date -u '+%Y-%m-%dT%H:%M UTC')/" \
            -e "1s/^# /## /" \
          | sed '1s/^/# Expected version change and release notes:\n/' \
          > /tmp/semantic-release-clean.txt

          if [ ! -s /tmp/semantic-release-clean.txt ]; then
            echo "# Expected version change and release notes" \
              > /tmp/semantic-release-clean.txt
            echo "## 🚨 WARNING: This PR is not expected to trigger a new version" \
              >> /tmp/semantic-release-clean.txt
            echo "To trigger a version bump, use at least one conventional commit message in this branch." \
              "See: https://www.conventionalcommits.org/en/v1.0.0/" \
              >> /tmp/semantic-release-clean.txt
          fi

      - name: preview semantic-release output for comment
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          cat /tmp/semantic-release-clean.txt

      - name: Find Comment
        if: ${{ github.event_name == 'pull_request' }}
        uses: peter-evans/find-comment@v4
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: "# Expected version change and release notes:"

      - name: Create or update comment
        if: ${{ github.event_name == 'pull_request' }}
        uses: peter-evans/create-or-update-comment@v5
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: /tmp/semantic-release-clean.txt
          edit-mode: replace
